import type { FilterParams, ColorMapping } from '../types'

export function generateFilterCSS(params: FilterParams): string {
  const filters: string[] = []

  if (params.invert) {
    filters.push('invert(1) hue-rotate(180deg)')
  }
  if (params.hueRotate !== 0) {
    filters.push(`hue-rotate(${params.hueRotate}deg)`)
  }
  if (params.brightness !== 100) {
    filters.push(`brightness(${params.brightness}%)`)
  }
  if (params.contrast !== 100) {
    filters.push(`contrast(${params.contrast}%)`)
  }
  if (params.saturate !== 100) {
    filters.push(`saturate(${params.saturate}%)`)
  }

  return filters.join(' ')
}

export function generateReverseFilterCSS(): string {
  return 'invert(1) hue-rotate(180deg)'
}

export function generateRootVariables(params: FilterParams): string {
  return `:root {
  --dm-invert: ${params.invert ? '1' : '0'};
  --dm-brightness: ${params.brightness}%;
  --dm-contrast: ${params.contrast}%;
  --dm-hue-rotate: ${params.hueRotate}deg;
  --dm-saturate: ${params.saturate}%;
  --dm-filter: ${generateFilterCSS(params)};
}`
}

export function generateColorMappingCSS(mappings: ColorMapping[]): string {
  const enabledMappings = mappings.filter((m) => m.enabled)
  if (enabledMappings.length === 0) return ''

  const rules: string[] = []

  enabledMappings.forEach((mapping) => {
    const selector = mapping.selector.trim() || 'body'
    const applyTo = mapping.applyTo ?? 'both'
    const decls: string[] = []
    if (applyTo === 'both' || applyTo === 'color') decls.push(`color: ${mapping.toColor} !important;`)
    if (applyTo === 'both' || applyTo === 'background') decls.push(`background-color: ${mapping.toColor} !important;`)
    rules.push(`${selector} {
  --dm-color-${mapping.id}-from: ${mapping.fromColor};
  --dm-color-${mapping.id}-to: ${mapping.toColor};
  ${decls.join('\n  ')}
}`)
  })

  return rules.join('\n\n')
}

export function generateFullDarkModeCSS(
  params: FilterParams,
  mappings: ColorMapping[],
  useMediaQuery: boolean = true
): string {
  const lines: string[] = []

  lines.push('/* ========================================')
  lines.push('   Dark Mode CSS - Generated by Previewer')
  lines.push('   ======================================== */')
  lines.push('')

  lines.push(generateRootVariables(params))
  lines.push('')

  if (params.invert) {
    const filterRule = generateFilterCSS(params)
    const reverseFilter = generateReverseFilterCSS()
    const wrapper = useMediaQuery
      ? `@media (prefers-color-scheme: dark) {
  html {
    filter: ${filterRule};
  }

  img, picture, video, canvas, svg, iframe,
  [style*="background-image"],
  [data-darkmode-ignore] {
    filter: ${reverseFilter};
  }
}`
      : `html.dark {
  filter: ${filterRule};
}

html.dark img, html.dark picture, html.dark video, html.dark canvas, html.dark svg, html.dark iframe,
html.dark [style*="background-image"],
html.dark [data-darkmode-ignore] {
  filter: ${reverseFilter};
}`

    lines.push(wrapper)
    lines.push('')
  }

  const mappingCSS = generateColorMappingCSS(mappings)
  if (mappingCSS) {
    lines.push('/* Custom Color Mappings */')
    if (useMediaQuery) {
      lines.push('@media (prefers-color-scheme: dark) {')
      lines.push('  ' + mappingCSS.split('\n').join('\n  '))
      lines.push('}')
    } else {
      lines.push('html.dark {')
      lines.push('  ' + mappingCSS.split('\n').join('\n  '))
      lines.push('}')
    }
    lines.push('')
  }

  lines.push('/* Background Overrides */')
  const bgOverrides = useMediaQuery
    ? `@media (prefers-color-scheme: dark) {
  body {
    background-color: #1a1a1a !important;
    color: #e0e0e0 !important;
  }

  a {
    color: #8ab4f8 !important;
  }

  a:visited {
    color: #c58af9 !important;
  }
}`
    : `html.dark body {
  background-color: #1a1a1a !important;
  color: #e0e0e0 !important;
}

html.dark a {
  color: #8ab4f8 !important;
}

html.dark a:visited {
  color: #c58af9 !important;
}`

  lines.push(bgOverrides)
  lines.push('')

  lines.push('/* Transition Support */')
  lines.push(`html, body, *, *::before, *::after {
  transition: background-color 0.3s ease, color 0.3s ease, border-color 0.3s ease;
}`)

  return lines.join('\n')
}

export function copyToClipboard(text: string): Promise<boolean> {
  if (navigator.clipboard) {
    return navigator.clipboard
      .writeText(text)
      .then(() => true)
      .catch(() => false)
  }
  return Promise.resolve(false)
}

export function downloadCSS(content: string, filename: string = 'dark-mode.css'): void {
  const blob = new Blob([content], { type: 'text/css;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
